spring.application.name=meowa
spring.datasource.url=jdbc:mysql://localhost:3306/meowa
spring.datasource.username=root
spring.datasource.password= abobapridurok
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true